### ISSUE TITLE
Also use GEOmetadb to attempt to match run info to dbGap

### ISSUE THREAD

**Issue by davemcg** [NCBI-Hackathons/ComplexPhenotypes#6]
https://www.bioconductor.org/packages/devel/bioc/html/GEOmetadb.html

GEO holds SNP arrays, right? I assume there are a lot of those in dbGap

**Comment by davemcg** [comment]
@seandavi

**Comment by jameslhao** [comment]
GEO only holds expression arrays. All individual level SNP array and some expression array data are hosted at dbGaP. Only small portion of GEO data are also submitted dbGaP.
Hope it helps.
Luning

**Comment by davemcg** [comment]
I'm just going to assume that dbGap holds zero info metadata on SNP chips. Perhaps the CDE will have something?
